name: Deploy Application on AWS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p .ssh/
          echo "${{ secrets.SSH_KEY }}" > .ssh/aws_key
          chmod 600 .ssh/aws_key
          echo "Created the directory"

      - name: Deploy application
        run: |
          scp -i .ssh/aws_key deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~
          ssh -i .ssh/aws_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "./deploy.sh"
