name: Deploy Application on AWS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p .ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

      - name: Deploy application
        run: |
          scp -i .ssh/id_rsa deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}}:~
          ssh -i .ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}} "./deploy.sh"
